export const longEvents = [
  {
    title: "Oana's Birthday",
    date: "Mai 2024",
    photos: [
      "/images/events-long/ziua-oana/1.jpeg",
      "/images/events-long/ziua-oana/2.jpeg",
      "/images/events-long/ziua-oana/3.jpeg",
      "/images/events-long/ziua-oana/4.jpeg",
      "/images/events-long/ziua-oana/5.jpeg",
      "/images/events-long/ziua-oana/6.jpeg",
      "/images/events-long/ziua-oana/7.jpeg",
      "/images/events-long/ziua-oana/8.jpeg",
    ],
  },
  {
    title: "Botez Rebeca Maria",
    date: "Mai 2024",
    photos: [
      "/images/events-long/botez-rebeca-maria/1.jpeg",
      "/images/events-long/botez-rebeca-maria/2.jpeg",
      "/images/events-long/botez-rebeca-maria/3.jpeg",
      "/images/events-long/botez-rebeca-maria/4.jpeg",
      "/images/events-long/botez-rebeca-maria/5.jpeg",
      "/images/events-long/botez-rebeca-maria/6.jpeg",
      "/images/events-long/botez-rebeca-maria/7.jpeg",
      "/images/events-long/botez-rebeca-maria/8.jpeg",
      "/images/events-long/botez-rebeca-maria/9.jpeg",
      "/images/events-long/botez-rebeca-maria/10.jpeg",
      "/images/events-long/botez-rebeca-maria/11.jpeg",
      "/images/events-long/botez-rebeca-maria/12.jpeg",
      "/images/events-long/botez-rebeca-maria/13.jpeg",
      "/images/events-long/botez-rebeca-maria/14.jpeg",
      "/images/events-long/botez-rebeca-maria/15.jpeg",
      "/images/events-long/botez-rebeca-maria/16.jpeg",
      "/images/events-long/botez-rebeca-maria/17.jpeg",
      "/images/events-long/botez-rebeca-maria/18.jpeg",
      "/images/events-long/botez-rebeca-maria/19.jpeg",
      "/images/events-long/botez-rebeca-maria/20.jpeg",
      "/images/events-long/botez-rebeca-maria/21.jpeg",
      "/images/events-long/botez-rebeca-maria/22.jpeg",
      "/images/events-long/botez-rebeca-maria/23.jpeg",
      "/images/events-long/botez-rebeca-maria/24.jpeg",
      "/images/events-long/botez-rebeca-maria/25.jpeg",
      "/images/events-long/botez-rebeca-maria/26.jpeg",
      "/images/events-long/botez-rebeca-maria/27.jpeg",
      "/images/events-long/botez-rebeca-maria/28.jpeg",
    ],
  },
  {
    title: "Botez Andrei",
    date: "Iunie 2024",
    photos: [
      "/images/events-long/botez-andrei/1.jpeg",
      "/images/events-long/botez-andrei/2.jpeg",
      "/images/events-long/botez-andrei/3.jpeg",
      "/images/events-long/botez-andrei/4.jpeg",
      "/images/events-long/botez-andrei/5.jpeg",
      "/images/events-long/botez-andrei/6.jpeg",
      "/images/events-long/botez-andrei/7.jpeg",
      "/images/events-long/botez-andrei/8.jpeg",
      "/images/events-long/botez-andrei/9.jpeg",
      "/images/events-long/botez-andrei/10.jpeg",
      "/images/events-long/botez-andrei/11.jpeg",
      "/images/events-long/botez-andrei/12.jpeg",
      "/images/events-long/botez-andrei/13.jpeg",
      "/images/events-long/botez-andrei/14.jpeg",
      "/images/events-long/botez-andrei/15.jpeg",
      "/images/events-long/botez-andrei/16.jpeg",
      "/images/events-long/botez-andrei/17.jpeg",
      "/images/events-long/botez-andrei/18.jpeg",
      "/images/events-long/botez-andrei/19.jpeg",
      "/images/events-long/botez-andrei/20.jpeg",
    ],
  },
  {
    title: "Botez Amir",
    date: "Iunie 2024",
    photos: [
      "/images/events-long/botez-amir/1.jpeg",
      "/images/events-long/botez-amir/2.jpeg",
      "/images/events-long/botez-amir/3.jpeg",
      "/images/events-long/botez-amir/4.jpeg",
      "/images/events-long/botez-amir/5.jpeg",
      "/images/events-long/botez-amir/6.jpeg",
      "/images/events-long/botez-amir/7.jpeg",
      "/images/events-long/botez-amir/8.jpeg",
      "/images/events-long/botez-amir/9.jpeg",
      "/images/events-long/botez-amir/10.jpeg",
      "/images/events-long/botez-amir/11.jpeg",
      "/images/events-long/botez-amir/12.jpeg",
      "/images/events-long/botez-amir/13.jpeg",
    ],
  },
  {
    title: "Festivalul de Artă Odisee",
    date: "August 2024",
    photos: [
      "/images/events-long/arta-odisee/1.jpeg",
      "/images/events-long/arta-odisee/2.jpeg",
      "/images/events-long/arta-odisee/3.jpeg",
      "/images/events-long/arta-odisee/4.jpeg",
      "/images/events-long/arta-odisee/5.jpeg",
      "/images/events-long/arta-odisee/6.jpeg",
      "/images/events-long/arta-odisee/7.jpeg",
      "/images/events-long/arta-odisee/8.jpeg",
    ],
  },
];
