export const longEvents = [
  {
    title: "Oana's Birthday",
    date: "Mai 2024",
    photos: [
      "/images/events-long/ziua-oana/1.webp",
      "/images/events-long/ziua-oana/2.webp",
      "/images/events-long/ziua-oana/3.webp",
      "/images/events-long/ziua-oana/4.webp",
      "/images/events-long/ziua-oana/5.webp",
      "/images/events-long/ziua-oana/6.webp",
      "/images/events-long/ziua-oana/7.webp",
      "/images/events-long/ziua-oana/8.webp",
    ],
  },
  {
    title: "Botez Rebeca Maria",
    date: "Mai 2024",
    photos: [
      "/images/events-long/botez-rebeca-maria/1.webp",
      "/images/events-long/botez-rebeca-maria/2.webp",
      "/images/events-long/botez-rebeca-maria/3.webp",
      "/images/events-long/botez-rebeca-maria/4.webp",
      "/images/events-long/botez-rebeca-maria/5.webp",
      "/images/events-long/botez-rebeca-maria/6.webp",
      "/images/events-long/botez-rebeca-maria/7.webp",
      "/images/events-long/botez-rebeca-maria/8.webp",
      "/images/events-long/botez-rebeca-maria/9.webp",
      "/images/events-long/botez-rebeca-maria/10.webp",
      "/images/events-long/botez-rebeca-maria/11.webp",
      "/images/events-long/botez-rebeca-maria/12.webp",
      "/images/events-long/botez-rebeca-maria/13.webp",
      "/images/events-long/botez-rebeca-maria/14.webp",
      "/images/events-long/botez-rebeca-maria/15.webp",
      "/images/events-long/botez-rebeca-maria/16.webp",
      "/images/events-long/botez-rebeca-maria/17.webp",
      "/images/events-long/botez-rebeca-maria/18.webp",
      "/images/events-long/botez-rebeca-maria/19.webp",
      "/images/events-long/botez-rebeca-maria/20.webp",
      "/images/events-long/botez-rebeca-maria/21.webp",
      "/images/events-long/botez-rebeca-maria/22.webp",
      "/images/events-long/botez-rebeca-maria/23.webp",
      "/images/events-long/botez-rebeca-maria/24.webp",
      "/images/events-long/botez-rebeca-maria/25.webp",
      "/images/events-long/botez-rebeca-maria/26.webp",
      "/images/events-long/botez-rebeca-maria/27.webp",
      "/images/events-long/botez-rebeca-maria/28.webp",
    ],
  },
  {
    title: "Botez Andrei",
    date: "Iunie 2024",
    photos: [
      "/images/events-long/botez-andrei/1.webp",
      "/images/events-long/botez-andrei/2.webp",
      "/images/events-long/botez-andrei/3.webp",
      "/images/events-long/botez-andrei/4.webp",
      "/images/events-long/botez-andrei/5.webp",
      "/images/events-long/botez-andrei/6.webp",
      "/images/events-long/botez-andrei/7.webp",
      "/images/events-long/botez-andrei/8.webp",
      "/images/events-long/botez-andrei/9.webp",
      "/images/events-long/botez-andrei/10.webp",
      "/images/events-long/botez-andrei/11.webp",
      "/images/events-long/botez-andrei/12.webp",
      "/images/events-long/botez-andrei/13.webp",
      "/images/events-long/botez-andrei/14.webp",
      "/images/events-long/botez-andrei/15.webp",
      "/images/events-long/botez-andrei/16.webp",
      "/images/events-long/botez-andrei/17.webp",
      "/images/events-long/botez-andrei/18.webp",
      "/images/events-long/botez-andrei/19.webp",
      "/images/events-long/botez-andrei/20.webp",
    ],
  },
  {
    title: "Botez Amir",
    date: "Iunie 2024",
    photos: [
      "/images/events-long/botez-amir/1.webp",
      "/images/events-long/botez-amir/2.webp",
      "/images/events-long/botez-amir/3.webp",
      "/images/events-long/botez-amir/4.webp",
      "/images/events-long/botez-amir/5.webp",
      "/images/events-long/botez-amir/6.webp",
      "/images/events-long/botez-amir/7.webp",
      "/images/events-long/botez-amir/8.webp",
      "/images/events-long/botez-amir/9.webp",
      "/images/events-long/botez-amir/10.webp",
      "/images/events-long/botez-amir/11.webp",
      "/images/events-long/botez-amir/12.webp",
      "/images/events-long/botez-amir/13.webp",
    ],
  },
  {
    title: "Festivalul de Artă Odisee",
    date: "August 2024",
    photos: [
      "/images/events-long/arta-odisee/1.webp",
      "/images/events-long/arta-odisee/2.webp",
      "/images/events-long/arta-odisee/3.webp",
      "/images/events-long/arta-odisee/4.webp",
      "/images/events-long/arta-odisee/5.webp",
      "/images/events-long/arta-odisee/6.webp",
      "/images/events-long/arta-odisee/7.webp",
      "/images/events-long/arta-odisee/8.webp",
    ],
  },
  {
    title: "Botez Cristian-Ioan",
    date: "August 2024",
    photos: [
      "/images/events-long/botez-cristian-ioan/1.webp",
      "/images/events-long/botez-cristian-ioan/2.webp",
      "/images/events-long/botez-cristian-ioan/3.webp",
      "/images/events-long/botez-cristian-ioan/4.webp",
      "/images/events-long/botez-cristian-ioan/5.webp",
      "/images/events-long/botez-cristian-ioan/6.webp",
      "/images/events-long/botez-cristian-ioan/7.webp",
      "/images/events-long/botez-cristian-ioan/8.webp",
      "/images/events-long/botez-cristian-ioan/9.webp",
      "/images/events-long/botez-cristian-ioan/10.webp",
      "/images/events-long/botez-cristian-ioan/11.webp",
      "/images/events-long/botez-cristian-ioan/12.webp",
    ],
  },
];
