export const packages = [
  {
    title: "Pachet 3 ore",
    features: [
      "Fotografii nelimitate",
      "Printuri nelimitate",
      "Diferite formate de print 10x15 si 5x10",
      "Banda magnetica gratuita",
      "Grafica personalizata",
      "Accesorii / recuzita variata si amuzanta",
      "Asistent prezent pe toata perioada inchirierii",
      "Transmiterea tuturor fotografiilor",
      "Background la alegere - din stocul nostru",
      "Optional ALBUM-guestbook personalizat",
    ],
    price: 800,
  },
  {
    title: "Pachet 4 ore",
    features: [
      "Fotografii nelimitate",
      "Printuri nelimitate",
      "Diferite formate de print 10x15 si 5x10",
      "Banda magnetica gratuita",
      "Grafica personalizata",
      "Accesorii / recuzita variata si amuzanta",
      "Asistent prezent pe toata perioada inchirierii",
      "Transmiterea tuturor fotografiilor",
      "Background la alegere - din stocul nostru",
      "Optional ALBUM-guestbook personalizat",
    ],
    price: 1000,
  },
  {
    title: "Pachet 5 ore",
    features: [
      "Fotografii nelimitate",
      "Printuri nelimitate",
      "Diferite formate de print 10x15 si 5x10",
      "Banda magnetica gratuita",
      "Grafica personalizata",
      "Accesorii / recuzita variata si amuzanta",
      "Asistent prezent pe toata perioada inchirierii",
      "Transmiterea tuturor fotografiilor",
      "Background la alegere - din stocul nostru",
      "Optional ALBUM-guestbook personalizat",
    ],
    price: 1100,
  },
  {
    title: "Pachet 6 ore",
    features: [
      "Fotografii nelimitate",
      "Printuri nelimitate",
      "Diferite formate de print 10x15 si 5x10",
      "Banda magnetica gratuita",
      "Grafica personalizata",
      "Accesorii / recuzita variata si amuzanta",
      "Asistent prezent pe toata perioada inchirierii",
      "Transmiterea tuturor fotografiilor",
      "Background la alegere - din stocul nostru",
      "Optional ALBUM-guestbook personalizat",
    ],
    price: 1200,
  },
  {
    title: "Pachet 8 ore", // Updated from 7 to 8 hours
    features: [
      "Fotografii nelimitate",
      "Printuri nelimitate",
      "Diferite formate de print 10x15 si 5x10",
      "Banda magnetica gratuita",
      "Grafica personalizata",
      "Accesorii / recuzita variata si amuzanta",
      "Asistent prezent pe toata perioada inchirierii",
      "Transmiterea tuturor fotografiilor",
      "Background la alegere - din stocul nostru",
      "Optional ALBUM-guestbook personalizat",
    ],
    price: 1300,
    special: "BEST", // Special tag for the best package
  },
];
