import "../app/globals.css";
import { Inter as FontSans } from "next/font/google";
import Header from "../components/PageLayout";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "eXpert Photobooth",
  description: "Generated by Alex Vieru",
};

export default function PageLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
